services:
  - type: web
    name: mon-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render injecte automatiquement PORT, sinon fixe-le ici
